services:
  - type: web
    name: freight-ml-api
    runtime: python
    rootDir: MODEL
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
